// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxdddiaheswxgkoannri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4ZGRkaWFoZXN3eGdrb2FubnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTY3MTMsImV4cCI6MjA2NzAzMjcxM30.qSwGdy8IKbS3oasHREKniFGwpsM-Cay5BYUvkV2aC98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});